{% set name = "jupitest" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupitest-{{ version }}.tar.gz
  sha256: 6b272768a955a2f1cc985f104ebfd8daabe060d0cb3bc392e5c68d23b498ed4c

build:
  entry_points:
    - jupitest = jupitest.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - tkf

test:
  imports:
    - jupitest
  commands:
    - pip check
    # CLI not quite implemented yet upstream
    # - jupitest --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/jupitest
  summary: Graphical Test Runner built with Pyrustic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
